development:
  adapter: mysql
  database: demo_app_develoment
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: demo_app_test
  username: root
  password: 
  host: localhost
    
production:
  adapter: mysql
  database: demo_app_production
  username: root
  password: 
  host: localhost
